export {
  verifyStaffCredentials,
  listTurnos,
  getTurnoById,
  createTurno,
  updateTurno,
  listClientes,
  createCliente,
  listMascotas,
  createMascota,
  listConsultasByMascota,
  upsertConsultaForTurno,
  getCatalog,
  switchSucursalActiva,
} from "@/lib/repos/postgresStore";
